image: 
  name: ${DOCKER_REPO}/softwareplumbers/gradle-centos:0.3.0
  entrypoint: ["/bin/bash", "-l", "-c"]
  
stages:
  - build 
  - publish
  
variables:
  JDK_HOME: /etc/alternatives/java_sdk_1.8.0 

build:
  stage: build
  artifacts:
    when: always
    paths:
      - build
  script:
   - gradle -P ci_version=${CI_COMMIT_REF_NAME} -P mavenUploadUser=${MAVEN_UPLOAD_USER} -P mavenUploadPassword=${MAVEN_UPLOAD_PASSWORD} -Dorg.gradle.java.home=${JDK_HOME} build
     
publish:
  stage: publish
  script:
   - gradle -P ci_version=${CI_COMMIT_REF_NAME} -P mavenUploadUser=${MAVEN_UPLOAD_USER} -P mavenUploadPassword=${MAVEN_UPLOAD_PASSWORD} -Dorg.gradle.java.home=${JDK_HOME} uploadArchives
   
